### ISSUE TITLE
Deprecated flow config_entry is set explicitly, will stop working in HA 2025.12

### ISSUE THREAD

**Issue by shadow1runner** [marq24/ha-goecharger-api2#32]
### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I understand the SHIT-__IN__ - SHIT-__OUT__ principle (in case of implausible data) | It will happen, that the data that is displayed by this integration does not make much sense (to you) - aka the data is not plausible. __Of course__ it could be the case, that something in this integration has been messed up - but so far - in all reported issues the root cause of implausible data was/is, that the go-eCharger device itself already provided this data [you can check this by directly requesting the attribute from the wallbox]
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

Many thanks for the integration!
I'm just getting started and reading the logs upon starting HA prints the following message:

> Detected that custom integration 'goecharger_api2' sets option flow config_entry explicitly, which is deprecated at custom_components/goecharger_api2/config_flow.py, line 204: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/marq24/ha-goecharger-api2/issues

**Comment by marq24** [comment]
pls update to latest release
