### ISSUE TITLE
Provide switch entity to allow charging

### ISSUE THREAD

**Issue by JakobTewes** [marq24/ha-goecharger-api2#5]
### Description

With my old hw v1 Go-E Charger, there was a switch entity to enable/disable charging.
Would be great, having an entity, that can control charging.

Thanks and regards

Jakob

**Comment by JakobTewes** [comment]
[This integration](https://github.com/syssi/homeassistant-goecharger-mqtt) provides a switch based on field "frc". 
Pls [see here](https://github.com/syssi/homeassistant-goecharger-mqtt?tab=readme-ov-file#buttons)

**Comment by marq24** [comment]
The 'frc' entitie is part of this integration - it's a selection - if it does not appear in our setup you shoul provide DEBUG log information

**Comment by JakobTewes** [comment]
Can confirm. The sensors now shine up...for my Gemini Flex this took overnight ;-(
