### ISSUE TITLE
Provide number entity to set charging kw limit

### ISSUE THREAD

**Issue by JakobTewes** [marq24/ha-goecharger-api2#6]
### Description

With my old hw v1 Go-E Charger, there was a number entity to set the max current.
Would be great, having an entity, that can control max current (preferrable ranging from 1p with 6 kw to 3p with 22kw.

**Comment by marq24** [comment]
same as #5 - API Key 'amp' is fully supported (same as ama and mca)

**Comment by JakobTewes** [comment]
Can confirm. The sensors now shine up...for my Gemini Flex this took overnight ;-(
